name: Test durations

on:
  workflow_dispatch:

env:
  PLATFORM_NAME_AMD64: "amd64"
  PLATFORM_NAME_ARM64: "arm64"
  
jobs:
  report:
    name: "Upload coverage"
    runs-on: ubuntu-latest
    steps:
        # Preparation for test
        - uses: actions/download-artifact@v4
          with:
            run-id: 15481533644
            repository: localstack/localstack
            github-token: ${{ secrets.GH_TOKEN_FORKD }}
            name: pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1
            path: artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1
            
        - name: List files in the repository
          run: |
            ls -la
            ls -la artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1/

        
        - name: Move
          run: |
            mv artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1/.test_durations \
              artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-1

        - uses: actions/upload-artifact@v4
          with:
            name: pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1
            path: artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-1
            include-hidden-files: true

        - uses: actions/download-artifact@v4
          with:
            run-id: 15481533644
            repository: localstack/localstack
            github-token: ${{ secrets.GH_TOKEN_FORKD }}
            name: pytest-split-durations-amd64-2
            path: artifacts/pytest-split-durations-amd64-2


        
        - name: Move
          run: |
            mv artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-2/.test_durations \
              artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-2/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-2


        - uses: actions/upload-artifact@v4
          with:
            name: pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-2
            path: artifacts/pytest-split-durations-amd64-2/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-2
            include-hidden-files: true

        - uses: actions/download-artifact@v4
          with:
            run-id: 15481533644
            repository: localstack/localstack
            github-token: ${{ secrets.GH_TOKEN_FORKD }}
            name: pytest-split-durations-amd64-3
            path: artifacts/pytest-split-durations-amd64-3


        
        - name: Move
          run: |
            mv artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-3/.test_durations \
              artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-3/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-3


        - uses: actions/upload-artifact@v4
          with:
            name: pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-3
            path: artifacts/pytest-split-durations-amd64-3/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-3
            include-hidden-files: true

        - uses: actions/download-artifact@v4
          with:
            run-id: 15481533644
            repository: localstack/localstack
            github-token: ${{ secrets.GH_TOKEN_FORKD }}
            name: pytest-split-durations-amd64-4
            path: artifacts/pytest-split-durations-amd64-4


        
        - name: Move
          run: |
            mv artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-4/.test_durations \
              artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-4/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-4


        - uses: actions/upload-artifact@v4
          with:
            name: pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-4
            path: artifacts/pytest-split-durations-amd64-4/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-4
            include-hidden-files: true

# Real test

        - name: Load test durations
          uses: actions/download-artifact@v4
          with:
            pattern: pytest-split-durations-*
            path: artifacts-test-durations
            merge-multiple: true


        - uses: actions/checkout@v4

        
        - name: Combine test durations results
          shell: bash
          run: |
            ls -la
            jq -s 'add' artifacts-test-durations/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}*  > .test_durations || echo "::warning::Test durations were not combined for ${{ env.PLATFORM_NAME_AMD64 }}"
            ls -la

        - uses: actions/upload-artifact@v4
          with:
            name: pytest-merged-durations
            path: .test_durations
            include-hidden-files: true
            if-no-files-found: error

        - name: Create PR
          uses: peter-evans/create-pull-request@v7
          if: ${{ success() }}
          with:
            title: "Update Test Durations"
            body: "Update test durations file"
            branch: "test-durations-auto-updates"
            author: "LocalStack Bot <localstack-bot@users.noreply.github.com>"
            committer: "LocalStack Bot <localstack-bot@users.noreply.github.com>"
            commit-message: "update .test_durations to latest version"
            add-paths: .test_durations
            labels: "semver: patch" #area: asf, area: dependencies, 
            token: ${{ secrets.GH_CREATE_PR }}
            reviewers: k-a-il
