name: Test durations

on:
  workflow_dispatch:
    inputs:
      publishMethod:
        description: 'Select how to publish the workflow result'
        type: choice
        options:
          - UPLOAD_ARTIFACT
          - CREATE_PR
        default: UPLOAD_ARTIFACT
env:
  # Take test durations only for this platform
  PLATFORM: "amd64"
  PLATFORM_NAME_AMD64: "amd64"

jobs:
  report:
    name: "Upload coverage"
    runs-on: ubuntu-latest
    steps:
        # Preparation for test
        - uses: actions/download-artifact@v4
          with:
            run-id: 15481533644
            repository: localstack/localstack
            github-token: ${{ secrets.GITHUB_TOKEN }}
            name: pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1
            path: artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1
            
        - name: List files in the repository
          run: |
            ls -la
            ls -la artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1/

        
        - name: Move
          run: |
            mv artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1/.test_durations \
              artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-1

        - uses: actions/upload-artifact@v4
          with:
            name: pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1
            path: artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-1/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-1
            include-hidden-files: true

        - uses: actions/download-artifact@v4
          with:
            run-id: 15481533644
            repository: localstack/localstack
            github-token: ${{ secrets.GITHUB_TOKEN }}
            name: pytest-split-durations-amd64-2
            path: artifacts/pytest-split-durations-amd64-2


        
        - name: Move
          run: |
            mv artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-2/.test_durations \
              artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-2/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-2


        - uses: actions/upload-artifact@v4
          with:
            name: pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-2
            path: artifacts/pytest-split-durations-amd64-2/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-2
            include-hidden-files: true

        - uses: actions/download-artifact@v4
          with:
            run-id: 15481533644
            repository: localstack/localstack
            github-token: ${{ secrets.GITHUB_TOKEN }}
            name: pytest-split-durations-amd64-3
            path: artifacts/pytest-split-durations-amd64-3


        
        - name: Move
          run: |
            mv artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-3/.test_durations \
              artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-3/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-3


        - uses: actions/upload-artifact@v4
          with:
            name: pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-3
            path: artifacts/pytest-split-durations-amd64-3/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-3
            include-hidden-files: true

        - uses: actions/download-artifact@v4
          with:
            run-id: 15481533644
            repository: localstack/localstack
            github-token: ${{ secrets.GITHUB_TOKEN }}
            name: pytest-split-durations-amd64-4
            path: artifacts/pytest-split-durations-amd64-4


        
        - name: Move
          run: |
            mv artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-4/.test_durations \
              artifacts/pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-4/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-4


        - uses: actions/upload-artifact@v4
          with:
            name: pytest-split-durations-${{ env.PLATFORM_NAME_AMD64 }}-4
            path: artifacts/pytest-split-durations-amd64-4/.test_durations-${{ env.PLATFORM_NAME_AMD64 }}-4
            include-hidden-files: true

# Real test



        - uses: actions/checkout@v4
          with:
            path: localstack
        
        - name: Load test durations
          uses: actions/download-artifact@v4
          with:
            pattern: pytest-split-durations-${{ env.PLATFORM }}-*
            path: artifacts-test-durations
            merge-multiple: true

        - name: Merge test durations files
          shell: bash
          run: |
            jq -s 'add | to_entries | sort_by(.key) | from_entries' artifacts-test-durations/.test_durations-${{ env.PLATFORM }}*  > localstack/.test_durations || echo "::warning::Test durations were not merged"

        - name: Upload artifact with merged test durations
          uses: actions/upload-artifact@v4
          if: ${{ success() && inputs.publishMethod == 'UPLOAD_ARTIFACT' }}
          with:
            name: merged-test-durations
            path: localstack/.test_durations
            include-hidden-files: true
            if-no-files-found: error

        - name: Create PR
          uses: peter-evans/create-pull-request@v7
          if: ${{ success() && inputs.publishMethod != 'UPLOAD_ARTIFACT' }}
          with:
            title: "Update test durations"
            body: "This PR includes an updated `.test_durations` file, generated using the latest test durations for the platform based on the master branch"
            branch: "test-durations-auto-updates"
            author: "LocalStack Bot <localstack-bot@users.noreply.github.com>"
            committer: "LocalStack Bot <localstack-bot@users.noreply.github.com>"
            commit-message: "CI: update .test_durations to latest version"
            path: localstack
            add-paths: .test_durations
            labels: "semver: patch" #area: asf, area: dependencies, 
            token: ${{ secrets.GITHUB_TOKEN }}
