name: LocalStack - Feature catalog files

on:
  workflow_dispatch:
  pull_request_target:
    paths:
      - localstack-core/localstack/services/**
    types: [labeled, unlabeled, opened, edited, synchronize]
    # only enforce for PRs targeting the master branch
    branches:
    - master

jobs:
  check_file_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get List of changed service files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: localstack-core/localstack/services/**

      - name: Verify features.yml file exists
        run: |
          echo "Changed files ${{ steps.changed-files.outputs.all_changed_files }}"
          MISSING_FEATURES_FILE=0
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            service_folder=$(dirname "$file")
            if [ ! -f "$service_folder/features.yml" ]; then
              echo "❌ Missing features.yml in $service_folder"
              MISSING_FEATURES_FILE=1
            fi
          done

      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install pyyaml jsonschema

      - name: Check YAML file schema
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}"
          FEATURES_JSON_SCHEMA: "features_schema.json"
        run: python .github/scripts/validate_yaml.py


