name: LocalStack - Feature catalog files

on:
  pull_request_target:
    paths:
      - localstack-core/localstack/services/**
    types: [labeled, unlabeled, opened, edited, synchronize]
    # only enforce for PRs targeting the master branch
    branches:
    - master

jobs:
  check_file_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2

    - name: Process files changed in the current commit
      run: |
        changedFiles=$(git diff --name-only HEAD^)
        for file in $changedFiles; do
          echo "Processing file: $file"
        done
        

#    - name: Set up Python
#      uses: actions/setup-python@v5
#      with:
#        python-version: "3.11"

    - name: Check feature catalog file existence
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: "/localstack-core/localstack/services/*/features.yml"
        fail: false
        ignore_case: false
        follow_symbolic_links: false

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo Feature catalog files exist

