name: AWS Integration Tests

on:
  push:
    paths-ignore:
      - 'CODEOWNERS'
      - 'README.md'
      - '.gitignore'
      - '.git-blame-ignore-revs'
    branches-ignore:
      - master
  workflow_dispatch:
    inputs:
      disableCaching:
        description: 'Disable Caching'
        required: false
        type: boolean
        default: false
      PYTEST_LOGLEVEL:
        type: choice
        description: Loglevel for PyTest
        options:
          - DEBUG
          - INFO
          - WARNING
          - ERROR
          - CRITICAL
        default: WARNING
      disableTestSelection:
        description: 'Disable Test Selection'
        required: false
        type: boolean
        default: false
      randomize-aws-credentials:
        description: "Randomize AWS credentials"
        default: false
        required: false
        type: boolean
      onlyAcceptanceTests:
        description: "Run only acceptance tests"
        default: false
        required: false
        type: boolean
  workflow_call:
    inputs:
      disableCaching:
        description: 'Disable Caching'
        required: false
        type: boolean
        default: false
      PYTEST_LOGLEVEL:
        type: string
        required: false
        description: Loglevel for PyTest
        default: WARNING
      disableTestSelection:
        description: 'Disable Test Selection'
        required: false
        type: boolean
        default: false
      randomize-aws-credentials:
        description: "Randomize AWS credentials"
        default: false
        required: false
        type: boolean
      onlyAcceptanceTests:
        description: "Run only acceptance tests"
        default: false
        required: false
        type: boolean

env:
  PYTEST_LOGLEVEL: ${{ inputs.PYTEST_LOGLEVEL || 'WARNING' }}
  IMAGE_NAME: "localstack/localstack"
  TINYBIRD_DATASOURCE: "community_tests"
  TESTSELECTION_PYTEST_ARGS: "${{ !inputs.disableTestSelection && '--path-filter=dist/testselection/test-selection.txt ' || '' }}"

jobs:
  build:
    name: "Build Docker Image (${{ contains(matrix.runner, 'arm') && 'ARM64' || 'AMD64' }})"
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
        exclude:
          # skip the ARM integration tests in case we are not on the master and not on the upgrade-dependencies branch and forceARMTests is not set to true
          - runner: ${{ (github.ref != 'refs/heads/master' && github.ref != 'upgrade-dependencies' && inputs.forceARMTests == false) && 'ubuntu-24.04-arm' || ''}}
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: localstack
          # setuptools_scm requires the git history (at least until the last tag) to determine the version
          fetch-depth: 0

      - name: Build Image
        uses: localstack/localstack/.github/actions/build-image@master
        with:
          disableCaching: ${{ inputs.disableCaching == true && 'true' || 'false' }}
          dockerhubPullUsername: ${{ secrets.DOCKERHUB_PULL_USERNAME }}
          dockerhubPullToken: ${{ secrets.DOCKERHUB_PULL_TOKEN }}

  capture-not-implemented:
    name: "Capture Not Implemented"
    if: ${{ !inputs.onlyAcceptanceTests && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: build
    env:
      PLATFORM: 'amd64'
    steps:
#      - name: Login to Docker Hub
#        # login to DockerHub to avoid rate limiting issues on custom runners
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_PULL_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PULL_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # setuptools_scm requires the git history (at least until the last tag) to determine the version
          fetch-depth: 0

      - name: Load Localstack Docker Image
        uses: k-a-il/localstack/.github/actions/load-localstack-docker-from-artifacts@master
        with:
          platform: "${{ env.PLATFORM }}"

      - name: Install Community Dependencies
        run: make install-dev

      - name: Start LocalStack
        env:
          # add the GitHub API token to avoid rate limit issues
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_EVENTS: "1"
          DEBUG: 1
          IMAGE_NAME: "localstack/localstack:latest"
        run: |
          source .venv/bin/activate
          localstack start -d
          localstack wait -t 120 || (localstack logs && false)


      - name: Run capture-not-implemented
        run: |
          source .venv/bin/activate
          mkdir ../results
          python -m capture_notimplemented_responses ../results/

      - name: Print the logs
        run: |
          source .venv/bin/activate
          localstack logs

      - name: Stop localstack
        run: |
          source .venv/bin/activate
          localstack stop

      - name: Archive Capture-Not-Implemented Results
        uses: actions/upload-artifact@v4
        with:
          name: capture-notimplemented
          path: results/
          retention-days: 30
