name: Validate files defining AWS service features

on:
  pull_request_target:
    paths:
      - localstack-core/localstack/services/**
    types: [ labeled, unlabeled, opened, edited, synchronize ]
    # only enforce for PRs targeting the master branch
    branches:
      - master

jobs:
  validate-features-files:
      uses: localstack/meta/.github/workflows/pr-validate-features-files.yml@automation-features-files
      with:
        aws_services_path: 'localstack-core/localstack/services'
