name: Validate files defining AWS service features

on:
  pull_request:
    paths:
      - localstack-core/localstack/services/**
    branches:
      - master

jobs:
  validate-features-files:
      uses: k-a-il/localstack/.github/workflows/pr-validate-features-files.yml@master
      with:
        aws_services_path: 'localstack-core/localstack/services'
