name: Validate files defining AWS service features

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'To manually launch this workflow, provide the PR number'
        type: number
        required: false
      localstack_meta_ref:
        description: 'To manually launch this workflow, provide branch to checkout in the localstack/meta'
        type: string
        required: false

jobs:
  validate-features-files:
      uses: localstack/meta/.github/workflows/pr-validate-features-files.yml@automation-features-files
      with:
        aws_services_path: 'localstack-core/localstack/services'
        pr_number: 2
        localstack_meta_ref: automation-features-files
